require "data/setting.lua"
require "data/test_item_data.lua"
require "data/test_shop_data.lua"

require "model/QiData.lua"
require "model/qibag.lua"
require "model/qishop.lua"

require "utils/test_debug.lua"
require "utils/utils.lua"
require "utils/globals.lua"

require "controller/maincontroller.lua"
require "controller/uicontroller.lua"
require "controller/alertcontroller.lua"
require "controller/questcontroller.lua"
require "controller/bagcontroller.lua"
require "controller/consolecontroller.lua"
require "controller/tabteleportcontroller.lua"
require "controller/playerequipcontroller.lua"

-- require "model/qititem.lua"
require "GameRoom/GameEndPanel.lua"
require "GameRoom/GameStartPanel.lua"

require "UI/QiBagView/QiBagView.lua"
require "UI/QiShopView.lua"
require "UI/AttackInfoView.lua"
require "UI/QiMainView.lua"
require "UI/QiConsoleView.lua"
require "UI/QiTeleportView.lua"
require "UI/QiQuestView.lua"
require "UI/QiAlertGuildAlert.lua"

require "UI/GameMode/QiYaotaView.lua"
require "UI/GameMode/QiBossFightView.lua"
require "UI/GameMode/QiShadiView.lua"
require "UI/GameMode/QiWishView.lua"
require "UI/GameMode/QiXiulianView.lua"
require "UI/GameMode/QiFateRoomView.lua"
require "UI/GameMode/QiSuanmingView.lua"
